version: "2.1"

services:
  server:
    container_name: server
    volumes:
      - ./:/app
    build: .
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "3000:3000"


  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./:/app
    environment:
        POSTGRES_PASSWORD: 'db_password'
        POSTGRES_USER: 'db_user'
        POSTGRES_DB: 'pg_users'


volumes:
  user:
    driver: local
